name: submodenv
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - pip:
      - transformers
      - ftfy
      - regex
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/decile-team/submodlib.git
