name: submodenv
channels:
  - defaults
dependencies:
  - numpy
  - opencv
  - torchaudio
  - pillow
  - pip
  - pytorch
  - torchvision
  - tqdm
  - python=3.10
prefix: /backup/palak/miniconda3/envs/submodenv

